name: Promote Dev to Test and Prod
on: workflow_dispatch

jobs:
  deploy-argo-test:
    uses: kartverket/smia-apps/.github/workflows/promote-app.yml@main
    with:
      application: kommuneinfo
      from_env: dev
      to_env: test
      namespace: smia-tjenester-main
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_ARGOCD }}

  deploy-argo-prod:
    uses: kartverket/smia-apps/.github/workflows/promote-app.yml@main
    with:
      application: kommuneinfo
      from_env: dev
      to_env: prod
      namespace: smia-tjenester-main
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_ARGOCD }}
